### ISSUE TITLE
Lost all jobs when redeploying or restarting web server

### ISSUE THREAD

**Issue by ghost** [percolatestudio/meteor-synced-cron#24]
When I kill and restart meteor on my localhost:3000, the jobs I created all disappeared. Is there a way for me to keep the jobs in memory, such as a MongoDB collection, and then to restart the jobs when the server boots up again?

**Comment by MurWade** [comment]
@zol so the application itself needs to keep its own collection of jobs and at meteor.start add them to the cron?

**Comment by artitw** [comment]
That's essentially what I ended up doing. Works fine for me

**Comment by zol** [comment]
@MurWade . Yes, although I think you may be using the package not quite how its intended. If you need to persist job data across runs, you'll need to use a collection as you said. SyncedCron is intended for running jobs that are controlled by time rather than state, such as "at 7am, send out a daily email to all registered users".

**Comment by MurWade** [comment]
@zol  i have always had the trouble of understanding how to  use a scheduler programmatically, this is not the first time. Thanks for your reply @artitw , makes me more confident what I am doing now.
