### ISSUE TITLE
How to log to Winston?

### ISSUE THREAD

**Issue by hanchang** [percolatestudio/meteor-synced-cron#43]
Since I'm using Papertrail to collect my Meteor application logs, I'd love to be able to send logging details from SyncedCron to Winston which will then forward to Papertrail. Is this supported and if so, how to integrate? Thanks!

**Comment by johanbrook** [comment]
This would be beneficial to us as well, since we're using our [`meteor-logger`](https://github.com/lookback/meteor-logger) package to send logs to Loggly.

The `Logger` in `meteor-synced-cron` can perhaps be injected as an option? Inside the package, just check for some key methods on the logger object (like `Logger.info`) before using it. I'll be happy to file a PR for this, or some other solution you find suitable.

**Comment by zol** [comment]
@johanbrook I would be happy to take a PR for this. Thanks.

**Comment by johanbrook** [comment]
@zol :+1: On it.
