### ISSUE TITLE
Jobs are being run twice

### ISSUE THREAD

**Issue by maartenbusstra** [percolatestudio/meteor-synced-cron#68]
Is this a known issue? I've checked to see if they get "add()"ed twice. But no, only once. I'll deploy one more time with logging enabled and post it here.

**Comment by maartenbusstra** [comment]
Oh, I don't believe I can have more debugging logs, right? Some more info: I'm basically only triggering some background work, which causes it to return quite fast without a return value. Maybe that could be the issue?

**Comment by maartenbusstra** [comment]
Found it! They were running twice when I had 'every 59 seconds' as parser.text argument.

**Comment by rb365** [comment]
Interesting, when I use parser.text sometimes it schedules job in the present/past and never runs it. Probably good idea to avoid parser.text?

**Comment by jasonswanson** [comment]
@maartenbusstra how did you fix this issue? did you increase the time between runs?

**Comment by maartenbusstra** [comment]
@jasonswanson I changed it to `every 1 minutes`.

**Comment by jasonswanson** [comment]
@maartenbusstra Thank you!

**Comment by maartenbusstra** [comment]
@jasonswanson Welcome! :) Sorry, I should've mentioned what I did to solve my issue.

**Comment by thebarty** [comment]
Yeah I got this, too when doing a 'every 1 minutes'.

Strange stuff, because @maartenbusstra: you described, that this actually fixed your issue. Can you post your configuration code?

```
  schedule(parser) {
    // parser is a later.parse object
    return parser.text('every 1 minutes')
  },
```

**Comment by dkoo761** [comment]
I also had this problem and discovered that the reason is due to how later.js (the underlying parser for synced-cron) handles the `every X seconds` situation. For example, `every 59 seconds` is treated as `Run at 0 seconds and at 59 seconds of each minute`.

So the schedule will be:
0m 0s
0m 59s
1m 0s
1m 59s
etc

Another example, the schedule for `every 25 seconds` will be:
0m 0s
0m 25s
0m 50s
1m 0s
1m 25s
1m 50s
etc

Using `every X seconds` only gives the expected result when 60 seconds is a multiple of X, so for example `every 20 seconds` and `every 30 seconds` works but `every 25 seconds` will not.

More info: https://github.com/bunkat/later/issues/60
